language: python
python:
  - "2.7"
virtualenv:
  system_site_packages: true
env:
  global:
  - SIMPHONYENV=~/simphony
  matrix:
  - TEST_SUITE=test-framework DEPS=apt-mayavi-deps PLUGINS=simphony-mayavi
  - TEST_SUITE=test-paraview DEPS=apt-paraview-deps PLUGINS=simphony-paraview
cache:
  pip: true
  directories:
  - $HOME/.ccache
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install ccache
  - ccache -s
  - export PATH=/usr/lib/ccache:${PATH}
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sudo make prepare $DEPS
  - sudo ln -s ccache /usr/local/bin/mpic++
install:
  - make prevenv
  - source ~/simphony/bin/activate
  - source /opt/openfoam/etc/bashrc
  - make postvenv
  - make $PLUGINS
  - make fix-simopenfoam
script:
  - pip freeze
  - ls -la ~/simphony/lib/python2.7/site-packages/
  - python -c "import simphonyfoaminterface"
  - python -m "import foam_controlwrapper"
  - make $TEST_SUITE
