language: python

python:
  - "2.7"
virtualenv:
  system_site_packages: true
env:
  global:
  - SIMPHONYENV=~/simphony
before_install:
  - sudo apt-get install ccache
  - ccache -s
  - export PATH=/usr/lib/ccache:${PATH}
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sudo make prepare
install:
  - make prevenv
  - source ~/simphony/bin/activate
  - source /opt/openfoam222/etc/bashrc
  - make postvenv
script:
  - make test-framework
