language: python

python:
  - "2.7"
virtualenv:
  system_site_packages: true
before_install:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sudo apt-get update -qq
  - sudo apt-get -y upgrade 
  - sudo make base apt-openfoam apt-simphony apt-lammps apt-mayavi fix-pip
install:
  - source /opt/openfoam222/etc/bashrc
  - make simphony-env
  - make -j 2 lammps jyu-lb
  - source ~/simphony/bin/activate
  - make simphony
  - make simphony-plugins
script:
  - make test-framework
