language: python

python:
  - "2.7"
virtualenv:
  system_site_packages: true
env:
  global:
  - SIMPHONYENV=~/simphony
  matrix:
  - TEST_SUITE=test-framework DEPS=apt-mayavi-deps PLUGINS=simphony-mayavi
  - TEST_SUITE=test-paraview DEPS=apt-paraview-deps PLUGINS=simphony-paraview
before_install:
  - sudo apt-get install ccache
  - ccache -s
  - export PATH=/usr/lib/ccache:${PATH}
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sudo make base
  - sudo make apt-openfoam-deps apt-simphony-deps apt-lammps-deps apt-aviz-deps $DEPS
  - make fix-pip
install:
  - make simphony-env
  - make aviz
  - make kratos
  - make lammps
  - make jyu-lb
  - make numerrin
  - source ~/simphony/bin/activate
  - source /opt/openfoam222/etc/bashrc
  - make simphony
  - make simphony-aviz
  - make simphony-jyu-lb
  - make simphony-lammps
  - make simphony-openfoam
  - make simphony-numerrin
  - make simphony-kratos
  - make $PLUGINS
  - make fix-simopenfoam
script:
  - make $TEST_SUITE
