language: python
python:
  - "2.7"
virtualenv:
  system_site_packages: true

matrix:
  include:
    - env: SIMPHONYENV=~/simphony TEST_SUITE=test-framework DEPS=apt-mayavi-deps PLUGINS=simphony-mayavi
    - env: SIMPHONYENV=~/simphony TEST_SUITE=test-paraview DEPS=apt-paraview-deps PLUGINS=simphony-paraview
    - dist: trusty
      env: SIMPHONYENV=~/simphony TEST_SUITE=test-framework DEPS=apt-mayavi-deps PLUGINS=simphony-mayavi
    - dist: trusty
      env: SIMPHONYENV=~/simphony TEST_SUITE=test-paraview DEPS=apt-paraview-deps PLUGINS=simphony-paraview
  allow_failures:
    - env: 

cache:
  pip: true
  directories:
  - $HOME/.ccache
before_install:
# Workaround for bogus additional job (travis-ci#4681). Proposed solutions didn't work
  - if [ ! ${SIMPHONYENV} ]; then false; fi;
  - sudo apt-get update -qq
  - sudo apt-get install ccache
  - ccache -s
  - export PATH=/usr/lib/ccache:${PATH}
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sudo make prepare $DEPS
  - sudo ln -s ccache /usr/local/bin/mpic++
install:
  - make prevenv
  - source ~/simphony/bin/activate
  - source /opt/openfoam222/etc/bashrc
  - make postvenv
  - make $PLUGINS
  - make fix-simopenfoam
script:
  - pip freeze
  - make $TEST_SUITE
