language: python
virtualenv:
  system_site_packages: true

matrix:
  include:
    - env: SIMPHONYENV=~/simphony TEST_SUITE=test-framework DEPS=apt-mayavi-deps PLUGINS=simphony-mayavi
      python: 2.7
    - env: SIMPHONYENV=~/simphony TEST_SUITE=test-paraview DEPS=apt-paraview-deps PLUGINS=simphony-paraview
      python: 2.7
    - env: SIMPHONYENV=~/simphony TEST_SUITE=test-framework DEPS=apt-mayavi-deps PLUGINS=simphony-mayavi
      dist: trusty
      python: 2.7
  allow_failures:
    - env: SIMPHONYENV=~/simphony TEST_SUITE=test-framework DEPS=apt-mayavi-deps PLUGINS=simphony-mayavi
      dist: trusty
      python: 2.7

cache:
  pip: true
  directories:
  - $HOME/.ccache
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install ccache
  - ccache -s
  - export PATH=/usr/lib/ccache:${PATH}
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sudo make prepare $DEPS
  - sudo ln -s ccache /usr/local/bin/mpic++
install:
  - make prevenv
  - source ~/simphony/bin/activate
  - source /opt/openfoam/etc/bashrc
  - make postvenv
  - make $PLUGINS
script:
  - pip freeze
  - make $TEST_SUITE
