language: python

python:
  - "2.7"
virtualenv:
  system_site_packages: true
env:
  - SIMPHONYENV=~/virtualenv/python2.7_with_system_site_packages
before_install:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sudo make base apt-openfoam apt-simphony apt-lammps apt-mayavi fix-pip
install:
  - source /opt/openfoam222/etc/bashrc
  - make -j 2 lammps jyu-lb
  - make simphony
  - make simphony-plugins
script:
  - make test-framework
