language: python

python:
  - "2.7"
virtualenv:
  system_site_packages: true
before_install:
  - sudo ./install_apt_requirements.sh
install:
  - . /opt/openfoam222/etc/bashrc
  - ./install_external.sh
  - ./install_simphony_packages.sh
script:
  - haas simphony -v
  - haas jyulb -v
  - haas simlammps -v
  - haas simphony_mayavi -v
  - haas tests/ -v
