language: python

python:
  - "2.7"
virtualenv:
  system_site_packages: true
before_install:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sudo make base apt-openfoam apt-simphony apt-lammps apt-mayavi
install:
  - . /opt/openfoam222/etc/bashrc
  - make simphony-env
  - source ~/simphony
  - make -j 2 lammps jyu-lb
  - make simphony
  - make simphony-plugins
script:
  - make test-framework
