language: python
virtualenv:
  system_site_packages: true
matrix:
  include:
    - env: SIMPHONYENV=~/simphony TEST_SUITE=test-framework 
      dist: trusty
      python: 2.7
cache:
  pip: true
  directories:
  - $HOME/.ccache
before_install:
  - deactivate
  - sudo apt-get update -qq
  - sudo apt-get install ccache
  - ccache -s
  - export PATH=/usr/lib/ccache:${PATH}
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sudo make deps
  - sudo ln -s ccache /usr/local/bin/mpic++
install:
  - make venv-prepare
  - source ~/simphony/bin/activate
  - make simphony
script:
  - pip freeze
  - pip install -r dev_requirements.txt
  - make $TEST_SUITE
