language: python

python:
  - "2.7"
virtualenv:
  system_site_packages: true
env:
  global:
  - SIMPHONYENV=~/simphony
before_install:
  - sudo apt-get install ccache
  - ccache -s
  - export PATH=/usr/lib/ccache:${PATH}
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sudo make base
  - sudo make apt-openfoam-deps apt-simphony-deps apt-lammps-deps apt-mayavi-deps apt-aviz-deps apt-nfluid-deps
  - make fix-pip
  # Get PySide wheel for nfluid (faster to install from wheel)
  - wget -q -O ${HOME}/PySide-1.2.4-cp27-cp27mu-linux_x86_64.whl https://github.com/simphony/simphony-framework/releases/download/0.2.2/PySide-1.2.4-cp27-cp27mu-linux_x86_64.whl
install:
  - make simphony-env
  - make aviz
  - make kratos
  - make lammps
  - make jyu-lb
  - make numerrin
  - source ~/simphony/bin/activate
  - source /opt/openfoam222/etc/bashrc
  - make simphony
  - make simphony-aviz
  - make simphony-jyu-lb
  - make simphony-lammps
  - make simphony-mayavi
  - make simphony-openfoam
  - make simphony-numerrin
  - make simphony-kratos
  # Install PySide for nfluid
  - pip install ~/PySide-1.2.4-cp27-cp27mu-linux_x86_64.whl
  - make nfluid
  - make fix-simopenfoam
script:
  - make test-framework
