language: python

python:
  - "2.7"
virtualenv:
  system_site_packages: true
env:
  global:
  - SIMPHONYENV=~/simphony
  matrix:
  - TEST_SUITE="test-framework"
  - TEST_SUITE="test-jyulb test-lammps test-openfoam test-kratos"
before_install:
  - sudo apt-get install ccache
  - ccache -s
  - export PATH=/usr/lib/ccache:${PATH}
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sudo make base
  - sudo make apt-openfoam-deps apt-simphony-deps apt-lammps-deps apt-mayavi-deps apt-aviz-deps
  - make fix-pip
install:
  - make simphony-env
  - make aviz
  - make kratos
  - make lammps
  - make jyu-lb
  - make numerrin
  - source ~/simphony/bin/activate
  - source /opt/openfoam222/etc/bashrc
  - make simphony
  - make simphony-aviz
  - make simphony-jyu-lb
  - make simphony-lammps
  - make simphony-mayavi
  - make simphony-openfoam
  - make simphony-numerrin
  - make simphony-kratos
  - make fix-simopenfoam
script:
  - make ${TEST_SUITE}
