language: python

python:
  - "2.7"
virtualenv:
  system_site_packages: true
env:
  - SIMPHONYENV=~/simphony
before_install:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sudo make base apt-openfoam apt-simphony apt-lammps apt-mayavi fix-pip
install:
  - make simphony-env
  - make -j 2 lammps jyu-lb numerrin
  - source ~/simphony/bin/activate
  - source /opt/openfoam222/etc/bashrc
  - echo $PATH
  - which wmake 
  - make simphony
  - make simphony-plugins
script:
  - make test-framework
